name: Rust Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install OpenSSL development headers
        run: sudo apt-get update && sudo apt-get install -y libssl-dev

      - name: Install Rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          profile: minimal

      - name: Build
        run: cargo build --release

      - name: Test
        run: cargo test --release

      - name: Archive binary
        uses: actions/upload-artifact@v2
        with:
          name: linux
          path: target/release/
