name: OS release

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        rust-version: [stable]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust-version }}
    - name: Build Project
      run: cargo build --release
    - name: Archive Artifact
      uses: actions/upload-artifact@v2
      with:
        name: gitfetch-${{ matrix.os }}
        path: target/release/gitfetch
  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: gitfetch-${{ matrix.os }}
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.0
        release_name: Release 1.0.0
        body: |
          This is the first release of gifetch.
        draft: false
        prerelease: false
    - name: Upload Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: target/release/gitfetch
        asset_name: gitfetch-${{ matrix.os }}
        asset_content_type: application/octet-stream
